### ISSUE TITLE
Don't enqueue admin styles on the frontend (or when not displaying the plugin settings page)

### ISSUE THREAD

**Issue by mundschenk-at** [dylandownhill/WP-Content-Security-Policy-Plugin#1]
Currently the plugin [enqueues a remote style unconditionally](https://github.com/dylandownhill/WP-Content-Security-Policy-Plugin/blob/master/wp-content-security-policy/trunk/admin/WP_CSP_Admin.php#L108) (even on the frontend!). In a plugin that's intended to increase security and control external resources, that's pretty bad.

I assume these resources are necessary for the settings page. In that case, you should a) include them in your plugin, b) only enqueue them in `admin_init` and c) only when actually displaying the settings page. There's even a WordPress hook for that, you can see [its use in wp-Typography](https://github.com/mundschenk-at/wp-typography/blob/master/includes/wp-typography/components/class-admin-interface.php#L416).

**Comment by mundschenk-at** [comment]
@dylandownhill This issue can be closed now 👍

**Comment by dylandownhill** [comment]
For anyone finding this topic later, the fix was to move the scripts from the init() function to the add_styles_and_scripts() function which is called form the action hook admin_enqueue_scripts. The function was further modified to only enqueue the scripts and styles if we're on the CSP setting page.
